[package]
name = "beagleeditor-cli"
version = "0.1.0"
authors = ["Mani Arasteh <mani.arasteh92@gmail.com"]
edition = "2021"

[[bin]]
name = "becli"
path = "src/main.rs"

[dependencies]
termion = "4.0.5"
unicode-segmentation = "1"

